name: Deploy server

on:
  push:
    branches:
      - test

jobs:
  job1:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: build image
        run: docker build -t $TAG_NAME .
        env:
          TAG_NAME: gcr.io/${{ secrets.PROJECT_NAME }}/example-app

      - name: authorization request to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: configure authentication
        run: gcloud auth configure-docker

      - name: push image
        run: docker push $TAG_NAME
        env:
          TAG_NAME: gcr.io/${{ secrets.PROJECT_NAME }}/example-app

      - name: check hash
        run: git rev-parse HEAD

      #- name: deploy
      #  run: gcloud run deploy test111 --project $PROJECT_NAME
      #  env:
      #    PROJECT_NAME: secrets.PROJECT_NAME
